name: ninjacheetah.dev
title: ninjacheetah.dev
url: https://ninjacheetah.dev
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
feed:
  posts_limit: 20
sass:
  load_paths:
    - assets/css
    - assets/bootstrap/css
collections:
  projects:
    output: true
